swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Django REST API
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1

# Paths supported by the server application
paths:
  /api/v1/auth/login:
    post:
      operationId: user.login
      tags:
        - Authentication
      summary: Acces for user
      description: User login for authencation
      parameters:
        - name: user
          in: body
          description: user login
          required: True
          schema:
            type: object
            properties:
              username:
                type: string
                description: First name of person to create
              password:
                type: string
                description: Last name of person to create
      responses:
        200:
          description: Successfully created person in list

  /api/v1/auth/logout:
    get:
      operationId: user.logout
      tags:
        - Authentication
      summary: User Logout
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Logout successfully
        401:
          description: Failed to logout

  /api/v1/auth/user:
    get:
      operationId: auth.user
      tags:
        - Authentication
      summary: Auth user information
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Get auth user obejct
          schema:
            properties:
              id:
                type: integer
                description: User ID
              username:
                type: string
              email:
                type: string
              first_name:
                type: string
              last_name:
                type: string


  /api/v1/auth/user/list:
    get:
      operationId: user.list
      tags:
        - User
      summary: Get user list
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Get auth user obejct
          schema:
            $ref: '#/definitions/Users'

definitions:
  Users:
    type: "array"
    items:
      $ref: '#/definitions/AuthUser'

  AuthUser:
    type: object
    properties:
      id:
        type: integer
        example: 1
      username:
        type: string
        example: 'username'
      email:
        type: string
        example: 'admin@example.com'
      first_name:
        type: string
        example: 'first name'
      last_Name:
        type: string
        example: 'last name'
