swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Django REST API
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1

# Paths supported by the server application
paths:
  /api/v1/auth/login:
    post:
      operationId: user.login
      tags:
        - Authentication
      summary: Acces for user
      description: User login for authencation
      parameters:
        - name: user
          in: body
          description: user login
          required: True
          schema:
            type: object
            properties:
              username:
                type: string
                description: First name of person to create
              password:
                type: string
                description: Last name of person to create
      responses:
        200:
          description: Successfully created person in list

  /api/v1/auth/logout:
    get:
      operationId: user.logout
      tags:
        - Authentication
      summary: User Logout
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Logout successfully
        401:
          description: Failed to logout

  /api/v1/auth/user:
    get:
      operationId: auth.user
      tags:
        - Authentication
      summary: Auth user information
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Get auth user obejct
          schema:
            $ref: '#/definitions/UserById'


  /api/v1/auth/user/list:
    get:
      operationId: user.list
      tags:
        - User
      summary: Get user list
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Get auth user obejct
          schema:
            $ref: '#/definitions/Users'

  /api/v1/auth/registration:
    post:
      operationId: user.create
      tags:
        - User
      summary: User Create
      description: User registration in this system
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: '#/definitions/UserCreate'
      responses:
        200:
          description: OK

  /api/v1/auth/<int:id>/user:
    get:
      operationId: user.byId
      tags:
        - User
      summary: Get user by id
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
          description: token.
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/UserById'
        404:
          description: User not found

definitions:
  Users:
    type: object
    properties:
      status:
        type: string
        example: 200
      users:
        type: array
        items:
          $ref: '#/definitions/UserList'

  UserList:
    type: object
    properties:
      id:
        type: integer
        example: 1
      username:
        type: string
        example: 'username'
      email:
        type: string
        example: 'admin@example.com'
      first_name:
        type: string
        example: 'first name'
      last_Name:
        type: string
        example: 'last name'

  UserCreate:
    type: object
    properties:
      username:
        type: string
        example: username
      email:
        type: string
        example: 'a@a.com'
      password:
        type: string
        example: "123456"
      first_name:
        type: string
        example: 'a'
      last_name:
        type: string
        example: 'a'
      is_superuser:
        type: boolean
        example: false
  UserById:
    properties:
      status:
        type: string
        example: 200
      user:
        type: object
        properties:
          id:
            type: integer
            example: 1
          username:
            type: string
            example: 'username'
          email:
            type: string
            example: 'admin@example.com'
          first_name:
            type: string
            example: 'first name'
          last_Name:
            type: string
            example: 'last name'
